; Sagar Paul 41
; 8086 program to subtract two 32-bit numbers

ASSUME CS: CODE, DS: DATA

DATA SEGMENT
    NUM1 DD 74975423H
    NUM2 DD 5634B758H
    RESULT DD ?
DATA ENDS

CODE SEGMENT
START:
    MOV AX, DATA
    MOV DS, AX
    CLC
    MOV CX, 0000H
    MOV DX, 0000H
    MOV AX, WORD PTR NUM1
    MOV BX, WORD PTR NUM2
    SUB AX, BX
    MOV WORD PTR RESULT, AX
    MOV AX, WORD PTR NUM1 + 2
    MOV BX, WORD PTR NUM2 + 2
    SBB AX, BX
    JNC NEXT
    INC CX
    CLC
    MOV BX, WORD PTR RESULT
    NOT BX
    ADD BX, 0001H
    JNC NOC
    INC DX
NOC:
    MOV WORD PTR RESULT, BX
    NOT AX
    ADD AX, DX
NEXT:
    MOV WORD PTR RESULT + 2, AX
    MOV WORD PTR RESULT + 4, CX
    MOV AH, 4CH
    INT 21H
CODE ENDS
END START